version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monapaste_dev
      POSTGRES_USER: monapaste_dev
      POSTGRES_PASSWORD: monapaste_dev
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    command: yarn dev
  studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 3001:5555
    command: npx prisma studio
volumes:
  postgres-data: {}
